addSbtPlugin("com.timushev.sbt"  % "sbt-updates"         % "0.6.4")
addSbtPlugin("com.github.sbt"    % "sbt-git"             % "2.1.0")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.11.7")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.10.0")
addSbtPlugin("org.typelevel"     % "laika-sbt"           % "1.3.2")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.6")
