addSbtPlugin("com.codecommit"    % "sbt-github-packages" % "0.5.3")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"         % "0.6.4")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"             % "1.0.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.7.5")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.10.0")
addSbtPlugin("org.planet42"      % "laika-sbt"           % "0.19.5")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.2")
